import glob
import os
import shutil
import subprocess
import sys


def build_cython_library():
    """Build the Cython library and clean up intermediate files."""

    print("Building Cython library...")

    # Remove old build
    if os.path.exists("octo"):
        shutil.rmtree("octo")
        print('Removed "octo" directory')

    # Build the extension
    result = subprocess.run(
        [sys.executable, "setup.py", "build_ext", "--build-lib", "."],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print("Build failed:")
        print(result.stderr)
        return False

    print("Build successful!")

    # Clean up intermediate files
    print("Cleaning up intermediate files...")

    # Remove .c files generated by Cython
    for f in glob.glob("src/**/*.c"):
        os.remove(f)
        print(f'Removed "{f}"')

    # Remove all Python files in the octo package
    for f in glob.glob("src/**/*.py"):
        os.remove(f)
        print(f'Removed "{f}"')

    print("Cleanup complete!")
    return True


if __name__ == "__main__":
    build_cython_library()
