import os
import shutil
import subprocess
import sys


def build_cython_library():
    """Build the Cython library and clean up intermediate files."""

    print("Building Cython library...")

    # Build the extension
    result = subprocess.run(
        [sys.executable, "setup.py", "build_ext", "--inplace"],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print("Build failed:")
        print(result.stderr)
        return False

    print("Build successful!")

    # Clean up intermediate files
    print("Cleaning up intermediate files...")

    # Remove .c files generated by Cython
    for file in os.listdir("."):
        if file.endswith(".c") and file.startswith("octo"):
            os.remove(file)
            print(f"Removed {file}")

    # Remove build directory
    if os.path.exists("build"):
        shutil.rmtree("build")
        print("Removed build directory")

    # # Remove the original .py file (optional - for distribution)
    # if os.path.exists("octo.py"):
    #     os.remove("octo.py")
    #     print("Removed original octo.py")

    print("Cleanup complete!")
    return True


if __name__ == "__main__":
    build_cython_library()
